=== albertfolch-redeemeum/dACP-agents-registry/schemas/v1.0.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/dACP-agent-config-schema.json",
  "title": "dACP Agent Configuration Schema v1.0.0",
  "description": "Schema for dACP agent configuration",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string",
      "format": "uuid",
      "description": "The unique identifier for the agent, typically a UUID."
    },
    "name": {
      "type": "string",
      "description": "The name of the dACP agent."
    },
    "description": {
      "type": "string",
      "description": "A brief description of the dACP agent, explaining its purpose and functionality."
    },
    "schemaVersion": {
      "type": "string",
      "description": "The version of the schema used for this agent configuration.",
      "enum": ["1.0.0"]
    },
    "entities": {
      "type": "array",
      "minItems": 0,
      "description": "List of BOSON PROTOCOL entities associated with the agent.",
      "items": {
        "type": "object",
        "properties": {
          "configId": {
            "type": "string",
            "description": "The configId of the BOSON PROTOCOL instance used by the agent for the specified entity and role. It refers to the environment (for instance \"staging\" or \"production\") and the chain (for instance 137 for Polygon or 8453 for Base).",
            "pattern": "^(local|testing|staging|production)-[0-9]+-[0-9]+$"
          },
          "role": {
            "type": "string",
            "description": "The role of the entity in the BOSON PROTOCOL, such as 'seller' or 'buyer'.",
            "enum": ["seller", "buyer", "disputeResolver", "marketplace", "royaltyRecipient", "other"]
          },
          "entityId": {
            "type": "string",
            "description": "The unique identifier for the entity within the BOSON PROTOCOL."
          },
          "signerAddress": {
            "type": "string",
            "description": "The Ethereum address of the signer for the entity. This address is used to sign transactions and messages related to the entity's role in the BOSON PROTOCOL.",
            "format": "ethereum-address"
          }
        },
        "required": ["configId", "role", "entityId", "signerAddress"],
        "additionalProperties": false
      }
    }
  },
  "required": ["uuid", "name", "description", "schemaVersion", "entities"],
  "additionalProperties": false
}

=== albertfolch-redeemeum/dACP-agents-registry/agents/local/e0ab3bdc-17c8-4cc8-b428-f55e87d76cc6-cotswolds.json
{
  "uuid": "e0ab3bdc-17c8-4cc8-b428-f55e87d76cc6",
  "schemaVersion": "1.0.0",
  "name": "Cotswolds",
  "description": "The Cotswolds Distillery Agent sells whisky and gin, direct from distilleries",
  "entities": [
    {
      "configId": "staging-80002-0",
      "role": "seller",
      "entityId": "123",
      "signerAddress": "0x1b05Ba94aCc29d0D66a0114a0bC7Daa139153BE5"
    },
    {
      "configId": "staging-11155111-0",
      "role": "seller",
      "entityId": "456",
      "signerAddress": "0x1b05Ba94aCc29d0D66a0114a0bC7Daa139153BE5"
    },
    {
      "configId": "staging-11155111-0",
      "role": "buyer",
      "entityId": "21",
      "signerAddress": "0x1b05Ba94aCc29d0D66a0114a0bC7Daa139153BE5"
    }
  ]
}

=== albertfolch-redeemeum/dACP-agents-registry/examples/ffffffff-ffff-ffff-ffff-ffffffffffff-example-agent.json
{
  "uuid": "ffffffff-ffff-ffff-ffff-ffffffffffff",
  "name": "example agent",
  "description": "The example agent is used to demonstrate the structure of an agent configuration.",
  "schemaVersion": "1.0.0",
  "entities": [
    {
      "configId": "staging-80002-0",
      "role": "seller",
      "entityId": "123",
      "signerAddress": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    },
    {
      "configId": "staging-11155111-0",
      "role": "seller",
      "entityId": "456",
      "signerAddress": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    },
    {
      "configId": "staging-11155111-0",
      "role": "buyer",
      "entityId": "21",
      "signerAddress": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    }
  ]
}
